version: '3'
services:
  app:
    build: .
    working_dir: /blog
    command: hugo server -v --bind "0.0.0.0" --port 1313 --themesDir /themes -t iara --watch --debug
    ports:
      - "1313:1313"
    volumes:
      - ./exampleSite:/blog
      - ./:/themes/iara
