version: '3'
services:
  app:
    build: .
    working_dir: /app/blog
    command: hugo server --logLevel info --bind "0.0.0.0" --port 1313 -c blob --themesDir /themes -t iara --watch
    ports:
      - "1313:1313"
    volumes:
      - ./:/themes/iara
