name = "Iara"
license = "MIT"
licenselink = "https://github.com/alexandrevicenzi/iara/blob/master/LICENSE.md"
description = "Clean and minimalist Medium-like theme for Hugo"
tags = ["blog", "responsive", "clean", "minimalist"]
features = ["blog", "seo", "responsive", "mobile", "disqus", "analytics"]
min_version = "0.65.0"

[author]
    name = "alexandrevicenzi"
    homepage = "http://alexandrevicenzi.com"
