baseurl = "https://example.com/"
languageCode = "en"
title = "Iara Theme"
defaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 10

# googleAnalytics = ""
# disqusShortname = ""

# [permalinks]
#   posts = "/:title"

[params]
mainSections = ["post"]
title = "Iara Theme"
description = "Example Blog"
images = ["/favicon.png"]
logo = "/favicon.png"
copyright = "Iara"
builtWith = false

  #
  # Author will show on sidebar
  #
  # [params.author]
  # name = "Iara"
  # bio = "Clean and minimalist, yet feature rich, Medium-like theme for Hugo built with Bootstrap"
  # image = "/android-chrome-512x512.png"

  #
  # License in the footer near copyright
  #
  [params.license]
  name = "CC BY-SA 4.0"
  url = "https://creativecommons.org/licenses/by-sa/4.0"

  #
  # Social Icons
  #
  [[params.social]]
  icon = "fab fa-twitter"
  title = "Twitter"
  url = "#"

  [[params.social]]
  icon = "fab fa-facebook-f"
  title = "Facebook"
  url = "#"

  [[params.social]]
  icon = "fab fa-instagram"
  title = "Instagram"
  url = "#"

  [[params.social]]
  icon = "fab fa-linkedin-in"
  title = "Linkedin"
  url = "#"

  [[params.social]]
  icon = "fab fa-github-alt"
  title = "GitHub"
  url = "https://github.com/alexandrevicenzi/iara"

  #
  # Sidebar
  #
  # Sidebar is hidden on small devices (< 576px)
  [params.sidebar]
    #
    # Change sidebar location
    #
    # location = "left" # default is right

    [params.sidebar.categories]
    show = true   # Show categories in sidebar
    count = true  # Show article count in category

    [params.sidebar.tags]
    show = true   # Show tags in sidebar
    count = false  # Show article count in tag

    #
    # Feature articles
    #
    [params.sidebar.featured]
    index = true  # Show index number

      [[params.sidebar.featured.item]]
      path = "post/markdown-syntax.md"

      [[params.sidebar.featured.item]]
      path = "post/math-typesetting.md"

      [[params.sidebar.featured.item]]
      path = "post/katex-support.md"

      [[params.sidebar.featured.item]]
      path = "post/emoji-support.md"

[taxonomies]
  author = "authors"
  category = "categories"
  series = "series"
  tag = "tags"

[menu]

  #
  # Main Menu
  #
  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 20
  url = "/contact/"

  [[menu.main]]
  name = ""
  weight = 1
  url = "/"
  pre = '<i class="fas fa-home"></i>'

  #
  # Dropdown Begin
  #
  # Only one level is supported
  # Dropdown URL has no effect if set
  [[menu.main]]
  name = "Dropdown"
  identifier = "dropdown"
  weight = 100

  [[menu.main]]
  parent = "dropdown"
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  parent = "dropdown"
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  parent = "dropdown"
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  parent = "dropdown"
  name = "Authors"
  weight = 400
  identifier = "authors"
  url = "/authors/"
  #
  # Dropdown End
  #

  [[menu.main]]
  name = "Hugo"
  weight = 999
  url = "https://gohugo.io/"

  #
  # Carousel menu (Home only)
  #
  [[menu.carousel]]
  name = "Customization"
  weight = 1
  url = "/tags/customization/"
  [[menu.carousel]]
  name = "Authors"
  weight = 2
  url = "/authors/"
  [[menu.carousel]]
  name = "Syntax"
  weight = 3
  url = "/categories/syntax/"
  [[menu.carousel]]
  name = "About"
  weight = 4
  url = "/about/"

  #
  # Terms & Diclaimers in footer
  #
  [[menu.terms]]
  name = "Terms of Use"
  weight = 1
  identifier = "terms"
  url = "#"

  [[menu.terms]]
  name = "Privacy"
  weight = 2
  identifier = "privacy"
  url = "#"

  [[menu.terms]]
  name = "GDPR"
  weight = 3
  identifier = "gdpr"
  url = "#"

  #
  # Footer section links
  #
  [[menu.footer1]]
  name = "Artificial Inteligence"
  weight = 1
  url = "#"
  pre = "<b>"
  post = "</b>"

  [[menu.footer1]]
  name = "Machine Learning"
  weight = 2
  url = "#"

  [[menu.footer1]]
  name = "Deep Learning"
  weight = 2
  url = "#"

  [[menu.footer1]]
  name = "Natural Language Processing"
  weight = 3
  url = "#"
  badge = "New"

  [[menu.footer1]]
  name = "Robotis"
  weight = 4
  url = "#"

  [[menu.footer2]]
  name = "SBCs"
  weight = 1
  url = "#"
  pre = "<b>"
  post = "</b>"

  [[menu.footer2]]
  name = "Raspbery Pi"
  weight = 2
  url = "#"
  post = '<span class="badge badge-pill badge-success">Discount</span>'

  [[menu.footer2]]
  name = "BeagleBone"
  weight = 3
  url = "#"

  [[menu.footer2]]
  name = "ODROID"
  weight = 4
  url = "#"

  [[menu.footer2]]
  name = "Micro Bit"
  weight = 5
  url = "#"

  [[menu.footer2]]
  name = "Arduino"
  weight = 6
  url = "#"

  [[menu.footer3]]
  name = "Linux"
  weight = 1
  url = "#"
  pre = "<b>"
  post = "</b>"

  [[menu.footer3]]
  name = "Ubuntu"
  weight = 3
  url = "#"
  post = '<span class="badge badge-warning">New</span>'

  [[menu.footer3]]
  name = "Arch"
  weight = 2
  url = "#"

  [[menu.footer3]]
  name = "Debian"
  weight = 4
  url = "#"

  [[menu.footer4]]
  name = "Careers"
  weight = 1
  identifier = "careers"
  url = "#"
  pre = "<b>"
  post = "</b>"

  [[menu.footer4]]
  name = "Contact"
  weight = 2
  identifier = "contact"
  url = "#"

  [[menu.footer4]]
  name = "Press Kit"
  weight = 3
  identifier = "press-kit"
  url = "#"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "github"
    tabWidth = 4
  # [markup.tableOfContents]
  #   endLevel = 3
  #   ordered = false
  #   startLevel = 2
